using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace Apilane.Portal.Api.V1.Contracts
{
    /// <summary>
    /// An application the signed-in user owns or collaborates on. It never carries the encryption
    /// key, the connection string or mail settings.
    /// </summary>
    public class ApplicationResponse
    {
        /// <summary>
        /// Identifies the application, in this API and on its API server (header x-application-token).
        /// </summary>
        [Required]
        public string Token { get; set; } = string.Empty;

        [Required]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Whether the API server accepts calls for the application.
        /// </summary>
        [Required]
        public bool Online { get; set; }

        /// <summary>
        /// Where the application's data lives: SQLLite, SQLServer, MySQL or PostgreSQL.
        /// </summary>
        [Required]
        public string DatabaseType { get; set; } = string.Empty;

        /// <summary>
        /// Whether a connection string is stored. The value itself is never returned. Always false
        /// for SQLLite, whose database file the API server names itself.
        /// </summary>
        [Required]
        public bool HasConnectionString { get; set; }

        /// <summary>
        /// The entity that splits the application's data per user group, or null when it has none.
        /// </summary>
        public string? DifferentiationEntity { get; set; }

        [Required]
        public int MaxAllowedFileSizeInKB { get; set; }

        /// <summary>
        /// True when the caller owns the application, false when it is shared with the caller.
        /// </summary>
        [Required]
        public bool IsOwner { get; set; }

        /// <summary>
        /// The e-mail address of the user who created the application.
        /// </summary>
        public string? OwnerEmail { get; set; }

        /// <summary>
        /// How many users the application is shared with. Null when the caller is not the owner:
        /// sharing is owner only.
        /// </summary>
        public int? CollaboratorCount { get; set; }

        /// <summary>
        /// How many custom endpoints the application has. Their SQL names entities and properties,
        /// so renaming one of those can break them.
        /// </summary>
        [Required]
        public int CustomEndpointCount { get; set; }

        /// <summary>
        /// The API server that hosts the application.
        /// </summary>
        [Required]
        public ServerSummaryResponse Server { get; set; } = new ServerSummaryResponse();
    }

    /// <summary>
    /// What a client needs to call an application on its API server. The only response of this API
    /// that carries the application's encryption key.
    /// </summary>
    public class ConnectionInfoResponse
    {
        [Required]
        public string Token { get; set; } = string.Empty;

        /// <summary>
        /// The address of the API server that hosts the application.
        /// </summary>
        [Required]
        public string ServerUrl { get; set; } = string.Empty;

        /// <summary>
        /// The key the application's encrypted properties are stored with. A secret: do not store or log it.
        /// </summary>
        [Required]
        public string EncryptionKey { get; set; } = string.Empty;
    }

    /// <summary>
    /// The values of a new application. Its token and its encryption key are generated by the Portal.
    /// </summary>
    public class CreateApplicationRequest
    {
        [Required(ErrorMessage = "Required")]
        [MinLength(4, ErrorMessage = "Must be 4 to 100 characters")]
        [MaxLength(100, ErrorMessage = "Must be 4 to 100 characters")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The API server that will host the application (GET /api/v1/servers). It cannot be changed later.
        /// </summary>
        [Required(ErrorMessage = "Required")]
        public long? ServerID { get; set; }

        /// <summary>
        /// Where the application's data will live: SQLLite, SQLServer, MySQL or PostgreSQL.
        /// </summary>
        [Required(ErrorMessage = "Required")]
        public string DatabaseType { get; set; } = string.Empty;

        /// <summary>
        /// The connection string of an empty, existing database. Required unless DatabaseType is
        /// SQLLite, which ignores it.
        /// </summary>
        public string? ConnectionString { get; set; }

        /// <summary>
        /// The name of the entity that splits the application's data per user group, e.g. Company.
        /// Empty or left out for none. It cannot be changed or removed later.
        /// </summary>
        [MaxLength(40, ErrorMessage = "Must be 40 characters or fewer")]
        public string? DifferentiationEntity { get; set; }
    }

    /// <summary>
    /// An exported application and where to put it, sent as multipart/form-data.
    /// </summary>
    public class ImportApplicationRequest
    {
        /// <summary>
        /// The application.json of an export (it is inside the downloaded zip). The application keeps
        /// the token and the encryption key it has in that file.
        /// </summary>
        [Required(ErrorMessage = "Required")]
        public IFormFile? File { get; set; }

        /// <summary>
        /// The API server that will host the application (GET /api/v1/servers).
        /// </summary>
        [Required(ErrorMessage = "Required")]
        public long? ServerID { get; set; }

        /// <summary>
        /// Where the application's data will live: SQLLite, SQLServer, MySQL or PostgreSQL.
        /// </summary>
        [Required(ErrorMessage = "Required")]
        public string DatabaseType { get; set; } = string.Empty;

        /// <summary>
        /// The connection string of an empty, existing database. Required unless DatabaseType is
        /// SQLLite, which ignores it.
        /// </summary>
        public string? ConnectionString { get; set; }
    }

    /// <summary>
    /// The values of an application that can be changed after it was created. The database type
    /// and the server cannot be changed: a DatabaseType or ServerID in the body is ignored.
    /// </summary>
    public class UpdateApplicationRequest
    {
        [Required(ErrorMessage = "Required")]
        [MinLength(4, ErrorMessage = "Must be 4 to 100 characters")]
        [MaxLength(100, ErrorMessage = "Must be 4 to 100 characters")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Write-only. Null or left out keeps the stored connection string; a value replaces it.
        /// Required when the application has none stored yet. Ignored for an SQLLite application.
        /// The API server does not check it: a wrong value shows when the application is next called.
        /// </summary>
        public string? ConnectionString { get; set; }
    }

    /// <summary>
    /// Whether the API server accepts calls for the application.
    /// </summary>
    public class SetApplicationStatusRequest
    {
        /// <summary>
        /// True takes the application online, false offline. Sending the current value changes nothing.
        /// </summary>
        [Required(ErrorMessage = "Required")]
        public bool? Online { get; set; }
    }
}
