name: Build-Push-Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      name: Check out code
  
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image for Api
      with:
        image: raptis/apilane
        tags: api-${{ github.ref_name }}
        registry: docker.io
        dockerfile: Apilane/Apilane.Web.Api/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildArgs: |
            VERSION=${{ github.ref_name }}

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image for Portal
      with:
        image: raptis/apilane
        tags: portal-${{ github.ref_name }}
        registry: docker.io
        dockerfile: Apilane/Apilane.Web.Portal/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildArgs: |
            VERSION=${{ github.ref_name }}
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Please refer to [CHANGELOG.md](https://github.com/raptisv/apilane/blob/main/CHANGELOG.md) for details.
        draft: false
        prerelease: false
